#TRIG 01, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 02, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 03, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 04, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 05, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 06, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 07, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 08, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 09, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 10, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 11, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 12, 2, 1, 1, 0, 1, 1, 0, ,
#TRIG 16, 2, 1, 2, 0, 0, 7, 0, 1, 16
********************************************************************
This file was generated by the WAV Trigger Init File Maker v1.00
It is only required if you wish to over-ride default settings. You
may add your own comments below this line -->
